### ISSUE TITLE
Tame of Thrones test file input and output is not matching

### ISSUE THREAD

**Issue by amalgta** [geektrust/coding-problem-artefacts#3]
The file content of input_2.txt is

```
AIR OWLAOWLBOWLC
LAND OFBBMUFDICCSO
ICE VTBTBHTBBBOBAB
WATER SUMMER IS COMING
```

and the content of output_2.txt is 

`NONE
`

but the content of the file is supposed to be

`SPACE LAND ICE
`

since the strings

OFBBMUFDICCSO (2 F's, 1 S, 1 I, 1 U) and VTBTBHTBBBOBAB (3 T's, 1 H, 1 V, 1 A, 1 O) is correct encoding of LAND and ICE respectively.

**Comment by dhanush** [comment]
You need three kingdoms to be allies to become the King. Hence it is `NONE`
