### ISSUE TITLE
Unknown property 'archiveBaseVersion' for task ':jar'

### ISSUE THREAD

**Issue by milofelipe** [geektrust/coding-problem-artefacts#7]
There seems to be no property named 'archiveBaseVersion'. I thought it was just a version issue but can't find any reference to that property in the docs.

https://github.com/geektrust/coding-problem-artefacts/blob/d9102cb97a326726d38e4b67d65426fc9a68b6ce/Java/build.gradle#L14

**Comment by dhanush** [comment]
It is there in Gradle 5.1 which we are supporting currently. We plan to update the Gradle versions soon. Then we will update the documentation appropriately.
