### ISSUE TITLE
Plugin 'org.apache.maven.plugins:maven-assembly-plugin:' not found

### ISSUE THREAD

**Issue by Prajapatkartik1** [geektrust/coding-problem-artefacts#9]
Hello, I have done Family Tree Problem but there is some issue with pom.xml file.
I am getting this error in my pom.xml file, " Plugin 'org.apache.maven.plugins:maven-assembly-plugin:' not found" . I am using IntelliJ Idea and I have tried invalidating the cache and also turned on plugin registry but still it is not working. Any suggestions

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>geektrust</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>15</maven.compiler.source>
        <maven.compiler.target>15</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <finalName>geektrust</finalName> 
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <appendAssemblyId>false</appendAssemblyId>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            
                            <mainClass>org.example.GeekTrustFamilyProblem</mainClass>
                        </manifest>
                    </archive>
                </configuration>

                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
        </plugins>
    </build>

</project>`

**Comment by dhanush** [comment]
> Hello, I have done Family Tree Problem but there is some issue with pom.xml file.
> I am getting this error in my pom.xml file, " Plugin 'org.apache.maven.plugins:maven-assembly-plugin:' not found" . I am using IntelliJ Idea and I have tried invalidating the cache and also turned on plugin registry but still it is not working. Any suggestions
> 
> `
> 
> 4.0.0
> 
> ```
> <groupId>org.example</groupId>
> <artifactId>geektrust</artifactId>
> <version>1.0-SNAPSHOT</version>
> 
> <properties>
>     <maven.compiler.source>15</maven.compiler.source>
>     <maven.compiler.target>15</maven.compiler.target>
> </properties>
> <dependencies>
>     <dependency>
>         <groupId>org.projectlombok</groupId>
>         <artifactId>lombok</artifactId>
>         <version>1.18.20</version>
>         <scope>provided</scope>
>     </dependency>
> </dependencies>
> <build>
>     <plugins>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-assembly-plugin</artifactId>
>             <configuration>
>                 <finalName>geektrust</finalName> 
>                 <descriptorRefs>
>                     <descriptorRef>jar-with-dependencies</descriptorRef>
>                 </descriptorRefs>
>                 <appendAssemblyId>false</appendAssemblyId>
>                 <archive>
>                     <manifest>
>                         <addClasspath>true</addClasspath>
>                         
>                         <mainClass>org.example.GeekTrustFamilyProblem</mainClass>
>                     </manifest>
>                 </archive>
>             </configuration>
> 
>             <executions>
>                 <execution>
>                     <id>make-assembly</id>
>                     <phase>package</phase>
>                     <goals>
>                         <goal>single</goal>
>                     </goals>
>                 </execution>
>             </executions>
>         </plugin>
>         
>     </plugins>
> </build>
> ```
> 
> `

Maven Assembly plugin is a very common maven plugin that is used. Please check [here](https://maven.apache.org/plugins/maven-assembly-plugin/index.html)
